import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles((theme) => ({
  root: {
    minHeight: '100vh',
    display: 'flex',
    width: '100%',
    background: '#F3F6F1',
    alignItems: 'stretch',
  },
  brandPanel: {
    display: 'none',
    [theme.breakpoints.up('md')]: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      width: '40%',
      padding: '56px',
      background:
        'linear-gradient(165deg, #0F3F0A 0%, #1F7A12 48%, #259311 78%, #3D7AB8 130%)',
      color: '#FFFFFF',
      gap: '18px',
      position: 'sticky',
      top: 0,
      height: '100vh',
      overflow: 'hidden',
    },
  },
  blob: {
    position: 'absolute',
    borderRadius: '50%',
    filter: 'blur(28px)',
    pointerEvents: 'none',
    '&.blobA': {
      width: '220px',
      height: '220px',
      background: 'rgba(255,255,255,0.18)',
      top: '-40px',
      right: '-30px',
      animation: 'tlcFloat 9s ease-in-out infinite',
    },
    '&.blobB': {
      width: '180px',
      height: '180px',
      background: 'rgba(78, 115, 190, 0.45)',
      bottom: '40px',
      left: '-40px',
      animation: 'tlcFloat 11s ease-in-out infinite reverse',
    },
  },
  brandLogo: {
    width: 'min(340px, 86%)',
    height: 'auto',
    display: 'block',
    background: '#FFFFFF',
    borderRadius: '24px',
    padding: '22px 28px',
    objectFit: 'contain',
    boxShadow: '0 18px 40px rgba(0, 0, 0, 0.18)',
    animation: 'tlcSlideUp 500ms ease both',
    zIndex: 1,
  },
  brandCopy: {
    fontSize: '16px !important',
    fontWeight: '500 !important',
    maxWidth: '380px',
    opacity: 0.94,
    animation: 'tlcSlideUp 620ms ease both',
    zIndex: 1,
  },
  featureList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '8px',
    zIndex: 1,
  },
  feature: {
    display: 'flex !important',
    alignItems: 'center',
    gap: '10px',
    fontSize: '14px !important',
    fontWeight: '600 !important',
    animation: 'tlcSlideUp 500ms ease both',
    '& svg': {
      fontSize: '20px',
    },
  },
  formColumn: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: '32px 24px',
    animation: 'tlcFadeIn 500ms ease both',
  },
  mainWrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '18px',
    padding: '32px 28px',
    width: '100%',
    maxWidth: '760px',
    backgroundColor: '#FFFFFF',
    borderRadius: '18px',
    boxShadow: '0 18px 50px rgba(27, 59, 20, 0.12)',
    border: '1px solid #E4EDE0',
    animation: 'tlcSlideUp 480ms ease both',
    [theme.breakpoints.down('sm')]: {
      padding: '28px 12px',
      boxShadow: 'none',
      border: 'none',
      background: 'transparent',
    },
  },
  logo: {
    width: '168px',
    objectFit: 'contain',
  },
  headingBlock: {
    textAlign: 'center',
  },
  welcome: {
    fontSize: '22px !important',
    fontWeight: '800 !important',
    color: '#163812',
    letterSpacing: '-0.03em !important',
  },
  header: {
    fontSize: '14px !important',
    fontWeight: '500 !important',
    color: '#5B6F56',
    marginTop: '4px !important',
    textAlign: 'center',
  },
  signupWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
    width: '100%',
  },
  signUpBtn_loginLink: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  loginLink: {
    fontSize: '13px !important',
    fontWeight: '500 !important',
    textAlign: 'center',
    '& .login': {
      textDecoration: 'none',
      color: '#259311',
      fontWeight: 700,
      '&:hover': {
        textDecoration: 'underline',
      },
    },
  },
}));
