import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles((theme) => ({
  root: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    background: '#faf6ef',
    animation: 'tlcFadeIn 280ms ease',
    [theme.breakpoints.down('sm')]: {
      padding: '20px 8px 13px 8px',
      height: 'auto',
      overflow: 'visible',
    },
  },
  welcome: {
    flexShrink: 0,
    background: '#5a7030',
    borderRadius: '10px',
    padding: '18px 22px',
    color: '#FFFFFF',
    boxShadow: '0 8px 18px rgba(90, 112, 48, 0.22)',
    '& .welcomeTitle': {
      fontSize: '20px',
      fontWeight: '700',
      lineHeight: 1.3,
    },
    '& .welcomeSub': {
      fontSize: '13px',
      fontWeight: '500',
      opacity: 0.92,
      marginTop: '4px',
    },
  },
  smallCardContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: '16px',
    flexShrink: 0,
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  smallCard: {
    display: 'flex !important',
    flexDirection: 'row',
    alignItems: 'center !important',
    justifyContent: 'flex-start !important',
    gap: '16px',
    width: '100%',
    minWidth: 0,
    minHeight: '112px',
    height: 'auto',
    boxSizing: 'border-box',
    padding: '20px 20px 20px 24px !important',
    borderRadius: '12px',
    background: '#FFFFFF',
    boxShadow: '0 4px 12px rgba(90, 80, 64, 0.08)',
    textAlign: 'left',
    textTransform: 'none',
    cursor: 'pointer',
    overflow: 'hidden',
    position: 'relative',
    transition: 'transform 180ms ease, box-shadow 180ms ease',
    '&::before': {
      content: '""',
      position: 'absolute',
      left: 0,
      top: '14px',
      bottom: '14px',
      width: '3px',
      borderRadius: '0 3px 3px 0',
      background: 'currentColor',
    },
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 8px 18px rgba(90, 80, 64, 0.12)',
    },
    '&:active': {
      transform: 'translateY(0)',
    },
    '&.volunteer': {
      color: '#7EAA55',
      background: 'linear-gradient(180deg, #FFFFFF 42%, #F1F7EC 100%)',
    },
    '&.enrollment': {
      color: '#DF8244',
      background: 'linear-gradient(180deg, #FFFFFF 42%, #FBF3EC 100%)',
    },
    '&.meeting': {
      color: '#9580C5',
      background: 'linear-gradient(180deg, #FFFFFF 42%, #F4F1F9 100%)',
    },
    '&.workshop': {
      color: '#a08040',
      background: 'linear-gradient(180deg, #FFFFFF 42%, #F8F3E8 100%)',
    },
    [theme.breakpoints.down('sm')]: {
      gap: '12px',
      minHeight: '104px',
      padding: '16px 14px 16px 20px !important',
    },
  },
  cardIcon: {
    width: '40px',
    height: '40px',
    flex: '0 0 40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '& svg': {
      display: 'block',
      width: '32px',
      height: '32px',
    },
  },
  cardCopy: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    minWidth: 0,
    '& .cardValue, & .cardTitle, & .cardCta': {
      margin: 0,
      padding: 0,
      textAlign: 'left',
    },
    '& .cardValue': {
      fontSize: '28px',
      fontWeight: '800',
      lineHeight: '32px',
      letterSpacing: '-0.03em',
      fontVariantNumeric: 'tabular-nums',
      color: 'inherit',
    },
    '& .cardTitle': {
      marginTop: '2px',
      fontSize: '13px',
      fontWeight: '600',
      lineHeight: '18px',
      color: '#3f382e',
    },
    '& .cardCta': {
      marginTop: '8px',
      fontSize: '12px',
      fontWeight: '700',
      lineHeight: '16px',
      color: 'inherit',
    },
  },
  // big cards
  bigCardContainer: {
    display: 'flex',
    gap: '20px',
    flex: 1,
    minHeight: 0,
    [theme.breakpoints.down('md')]: {
      flexDirection: 'column',
      overflow: 'auto',
    },
  },
  bigCard: {
    width: '50%',
    background: '#FFFFFF',
    boxShadow: 'rgba(109, 109, 109, 0.25) 0px 4px 10px',
    borderRadius: '5px',
    minHeight: 0,
    height: 'auto',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    padding: '20px',
    [theme.breakpoints.down('md')]: {
      width: '100%',
      height: '400px',
    },
    '& p.bigCardHeading': {
      fontWeight: '600',
      height: '30px',
    },
  },
  bigCardHeadingRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '30px',
    '& .seeAll': {
      fontSize: '12px',
      fontWeight: '700',
      color: '#3d4f1e',
      cursor: 'pointer',
      '&:hover': {
        textDecoration: 'underline',
      },
    },
  },

  upcominWorkshops: {
    flex: 1,
    minHeight: 0,
    height: 'auto',
    overflow: 'auto',
    display: 'flex',
    flexDirection: 'column',
    paddingTop: '10px',
    gap: '15px',
    '&::-webkit-scrollbar': {
      display: 'none',
    },
    '& .noWorkshop, .upcomingLoading': {
      fontSize: '12px',
      fontWeight: '500',
    },
  },

  chartMain: {
    flex: 1,
    minHeight: 0,
    height: 'auto',
    overflow: 'hidden',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
}));
