import { makeStyles } from '@mui/styles';
export const useStyles = makeStyles((theme) => ({
  root: {
    minHeight: '100vh',
    display: 'flex',
    width: '100%',
    background: '#F3F6F1',
  },
  brandPanel: {
    display: 'none',
    [theme.breakpoints.up('md')]: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      width: '44%',
      padding: '56px',
      background:
        'linear-gradient(165deg, #0F3F0A 0%, #1F7A12 48%, #259311 78%, #3D7AB8 130%)',
      color: '#FFFFFF',
      gap: '18px',
      position: 'relative',
      overflow: 'hidden',
    },
  },
  blob: {
    position: 'absolute',
    borderRadius: '50%',
    filter: 'blur(28px)',
    pointerEvents: 'none',
    '&.blobA': {
      width: '220px',
      height: '220px',
      background: 'rgba(255,255,255,0.18)',
      top: '-40px',
      right: '-30px',
      animation: 'tlcFloat 9s ease-in-out infinite',
    },
    '&.blobB': {
      width: '180px',
      height: '180px',
      background: 'rgba(78, 115, 190, 0.45)',
      bottom: '40px',
      left: '-40px',
      animation: 'tlcFloat 11s ease-in-out infinite reverse',
    },
  },
  brandLogo: {
    width: 'min(360px, 86%)',
    height: 'auto',
    display: 'block',
    background: '#FFFFFF',
    borderRadius: '24px',
    padding: '22px 28px',
    objectFit: 'contain',
    boxShadow: '0 18px 40px rgba(0, 0, 0, 0.18)',
    animation: 'tlcSlideUp 500ms ease both',
    zIndex: 1,
  },
  brandTitle: {
    fontSize: '28px !important',
    fontWeight: '800 !important',
    lineHeight: '1.15 !important',
    letterSpacing: '-0.03em !important',
    animation: 'tlcSlideUp 560ms ease both',
    animationDelay: '80ms',
    zIndex: 1,
  },
  brandCopy: {
    fontSize: '16px !important',
    fontWeight: '500 !important',
    maxWidth: '380px',
    opacity: 0.94,
    animation: 'tlcSlideUp 620ms ease both',
    animationDelay: '140ms',
    zIndex: 1,
  },
  featureList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '12px',
    zIndex: 1,
  },
  feature: {
    display: 'flex !important',
    alignItems: 'center',
    gap: '10px',
    fontSize: '14px !important',
    fontWeight: '600 !important',
    animation: 'tlcSlideUp 500ms ease both',
    '& svg': {
      fontSize: '20px',
    },
  },
  formColumn: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '32px 24px',
    animation: 'tlcFadeIn 500ms ease both',
  },
  mainWrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '22px',
    padding: '36px 32px',
    backgroundColor: '#FFFFFF',
    borderRadius: '18px',
    boxShadow: '0 18px 50px rgba(27, 59, 20, 0.12)',
    border: '1px solid #E4EDE0',
    animation: 'tlcSlideUp 480ms ease both',
    [theme.breakpoints.between('sm', 'md')]: {
      width: '80%',
    },
    [theme.breakpoints.down('sm')]: {
      padding: '40px 16px',
      width: '100%',
      boxShadow: 'none',
      border: 'none',
      background: 'transparent',
    },
  },
  logo: {
    width: '168px',
    objectFit: 'contain',
  },
  headingBlock: {
    textAlign: 'center',
  },
  welcome: {
    fontSize: '22px !important',
    fontWeight: '800 !important',
    color: '#163812',
    letterSpacing: '-0.03em !important',
  },
  header: {
    fontSize: '14px !important',
    fontWeight: '500 !important',
    color: '#5B6F56',
    marginTop: '4px !important',
    '& span': {
      color: '#259311',
      fontWeight: '700',
    },
  },
  formWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    width: '100%',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
  },
  fieldIcon: {
    fontSize: '18px !important',
    color: '#7A9274',
  },
  formControl: {
    [theme.breakpoints.down('md')]: { width: '100%' },
    width: '359px',
    display: 'flex',
    gap: '6px',
    '& label': {
      fontWeight: '600',
      fontSize: '13px',
      color: '#2F2F2F',
      '& .MuiFormLabel-asterisk': {
        color: theme.palette.primaryRed,
      },
    },
    '& .MuiInputBase-formControl': {
      border: '1px solid #D5E0D0',
      borderRadius: '12px',
      height: '46px',
      paddingRight: '10px',
      paddingLeft: '6px',
      backgroundColor: '#FBFDF9',
      transition:
        'border-color 180ms ease, box-shadow 180ms ease, background-color 180ms ease',
      '&:hover': {
        borderColor: '#B7CDB0',
        backgroundColor: '#FFFFFF',
      },
      '& input': {
        fontSize: '14px',
        padding: '8px 8px',
        '&:-webkit-autofill': {
          '-webkit-box-shadow': '0 0 0 100px #FBFDF9 inset',
        },
      },
      '& fieldset': {
        display: 'none',
      },
      '& .MuiInputAdornment-root button': {
        padding: '0px',
        '& svg': {
          width: '20px',
          height: '20px',
          color: '#2F2F2F',
        },
      },
    },
  },
  FormElementInBox: {
    display: 'flex',
    flexDirection: 'column',
    [theme.breakpoints.down('md')]: { width: '100%' },
    width: '359px',
    gap: '10px',
    '& .forgotPassword , p': {
      fontSize: '13px',
      color: '#4E73BE',
      fontWeight: '600',
      textDecoration: 'none',
    },
    '& p': { color: '#2F2F2F', fontWeight: 500 },
    '& .forgotPassword:hover, & .signup:hover': {
      textDecoration: 'underline',
    },
    '& .signup': {
      textDecoration: 'none',
      color: '#259311',
      fontWeight: 700,
    },
  },
  signInBtn: {
    height: '46px',
    width: '100%',
    borderRadius: '12px !important',
    textTransform: 'none !important',
    backgroundColor: '#259311 !important',
    color: '#ffffff !important',
    fontWeight: '700 !important',
    fontSize: '15px !important',
    position: 'relative',
    overflow: 'hidden',
    animation: 'tlcPulseSoft 2.8s ease-in-out infinite',
    '&::after': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '40%',
      height: '100%',
      background:
        'linear-gradient(90deg, transparent, rgba(255,255,255,0.28), transparent)',
      animation: 'tlcShine 2.6s ease-in-out infinite',
    },
    '&.continueBtn:hover': {
      backgroundColor: '#1F7A12 !important',
      filter: 'none',
    },
  },
}));
