import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles((theme) => ({
  gridContainer: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    '--ag-font-family': theme.typography.fontFamily,
    '--ag-font-size': `${theme.typography.fontSize}px`,
    '--ag-header-height': '46px',
    '--ag-row-height': '52px',
    '--ag-header-background-color': '#f2e8d8',
    '--ag-header-foreground-color': '#2a3814',
    '--ag-background-color': '#FFFFFF',
    '--ag-odd-row-background-color': '#F8FBF6',
    '--ag-row-hover-color': '#f2e8d8',
    '--ag-selected-row-background-color': '#e6dcc8',
    '--ag-border-color': 'transparent',
    '--ag-row-border-color': '#e6dcc8',
    '--ag-checkbox-checked-color': '#3d4f1e',
    '--ag-checkbox-unchecked-color': '#9AA89A',
    '--ag-range-selection-border-color': '#3d4f1e',
    '--ag-input-focus-border-color': '#3d4f1e',
    [theme.breakpoints.down('sm')]: {
      minHeight: '320px',
    },
  },
  row: {
    fontSize: '14px !important',
  },
  verified: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '78px',
    height: '24px',
    padding: '0 10px',
    borderRadius: '999px',
    background: '#f2e8d8',
    color: '#2a3814',
    fontSize: '14px !important',
    fontWeight: '700 !important',
    letterSpacing: '0.02em',
  },
  pending: {
    '&.MuiButton-root': {
      textTransform: 'capitalize',
      fontSize: '14px',
      minWidth: '78px',
      height: '24px',
      borderRadius: '999px',
      padding: '0 10px',
      background: '#FDECDC !important',
      color: '#C45A12',
      fontWeight: '700',
      boxShadow: 'none',
      '&:hover': {
        background: '#F9D7B8 !important',
        filter: 'none',
      },
    },
  },
  tableSkeleton: {
    minHeight: '100%',
    backgroundColor: 'white',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '10px',
    padding: '24px',
    '& svg': {
      color: theme.palette.primaryGreen,
    },
    '& .errorMessage': {
      color: '#6C6C6C',
      fontSize: '14px',
      fontWeight: '500',
    },
  },
  skeletonWrap: {
    flex: 1,
    padding: '12px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    background: '#FFFFFF',
  },
  skeletonRow: {
    height: '40px',
    borderRadius: '8px',
    background:
      'linear-gradient(90deg, #F1F4EE 0%, #E4EBE0 50%, #F1F4EE 100%)',
    backgroundSize: '200% 100%',
    animation: 'tlcShimmer 1.2s ease-in-out infinite',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    height: '100%',
    color: '#6C6C6C',
    '& strong': {
      fontSize: '14px',
      color: '#2F2F2F',
    },
    '& span': {
      fontSize: '14px',
    },
  },
  AgGridMain: {
    flex: 1,
    minHeight: 0,
    [theme.breakpoints.down('sm')]: {
      flex: 'none',
      height: 'auto',
      minHeight: 'auto',
    },
    '& .ag-root-wrapper': {
      border: 'none',
      borderRadius: '0px',
    },
    '& .ag-header': {
      backgroundColor: '#f2e8d8',
      border: 'none',
      borderBottom: '1px solid #e6dcc8',
      '& .ag-header-cell': {
        paddingLeft: '14px',
        paddingRight: '14px',
      },
      '& .ag-header-cell-text': {
        fontSize: '14px',
        color: '#3d3525',
        fontFamily: theme.typography.fontFamily,
        fontWeight: '600',
        letterSpacing: '0',
        textTransform: 'none',
        cursor: 'pointer',
      },
      '& .ag-pinned-right-header': {
        borderLeft: '1px solid #e6dcc8',
      },
    },
    '& .ag-header-cell-resize': {
      right: '6px',
      '&::after': {
        background: '#C5D6BE',
        width: '1px',
        height: '50%',
        top: '25%',
      },
    },
    '& .ag-row': {
      borderColor: '#e6dcc8',
      borderWidth: '0 0 1px 0',
      transition: 'background-color 120ms ease, box-shadow 120ms ease',
    },
    '& .ag-row-hover': {
      backgroundColor: '#f2e8d8 !important',
      cursor: 'pointer',
      boxShadow: 'inset 3px 0 0 #3d4f1e',
    },
    '& .ag-row-selected': {
      backgroundColor: '#e6dcc8 !important',
      boxShadow: 'inset 3px 0 0 #2a3814',
    },
    '& .ag-cell': {
      fontSize: '14px',
      color: '#3d3525',
      fontWeight: '500',
      textTransform: 'none',
      display: 'flex',
      alignItems: 'center',
      border: 'none !important',
      fontFamily: theme.typography.fontFamily,
      lineHeight: 1.3,
      paddingLeft: '14px',
      paddingRight: '14px',
    },
    '& .ag-cell-focus': {
      border: 'none !important',
      outline: 'none',
    },
    '& .ag-overlay-wrapper': {
      paddingTop: '0 !important',
      fontSize: '14px',
      color: '#3d3525',
      fontWeight: '500',
      fontFamily: theme.typography.fontFamily,
    },
    '& .ag-checkbox-input-wrapper': {
      boxShadow: 'none !important',
      fontSize: '16px',
      '&.ag-checked::after': {
        color: theme.palette.primaryGreen,
      },
      '&::after': {
        color: '#9AA89A',
      },
    },
    '& .ag-pinned-right-cols-container': {
      borderLeft: '1px solid #e6dcc8',
    },
    '& .ag-body-viewport': {
      background: '#FFFFFF',
    },
  },
  count: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '28px',
    height: '24px',
    padding: '0 8px',
    borderRadius: '999px',
    background: '#E8F0FA',
    color: '#005C8E',
    cursor: 'pointer',
    fontWeight: '700',
    fontSize: '14px',
    '&:hover': {
      background: '#D2E4F5',
    },
  },
  errorMessage: {
    color: '#6C6C6C',
    fontSize: '14px',
    fontWeight: '500',
  },
  nameCell: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    minWidth: 0,
    cursor: 'pointer',
  },
  avatar: {
    flexShrink: 0,
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    background: '#5a7030',
    color: '#FFFFFF',
    fontSize: '14px',
    fontWeight: '700',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    letterSpacing: '0.02em',
  },
  nameText: {
    color: '#2a3814',
    fontWeight: '600',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    '&:hover': {
      color: '#3d4f1e',
    },
  },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    height: '22px',
    padding: '0 10px',
    borderRadius: '999px',
    fontSize: '14px',
    fontWeight: '600',
    textTransform: 'capitalize',
    '&.male': {
      background: '#E7F0FA',
      color: '#1D4E89',
    },
    '&.female': {
      background: '#F8E8F1',
      color: '#8A2A5B',
    },
    '&.other': {
      background: '#F1F1F1',
      color: '#4A4A4A',
    },
  },
  tableHint: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 16px',
    fontSize: '14px !important',
    fontWeight: '500 !important',
    color: '#3d4f1e',
    background: '#F4F8F1',
    borderBottom: '1px solid #e6dcc8',
  },
}));
